import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Scrapccomponentes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-900 min-h-screen flex flex-col">
        <header className="bg-indigo-600 p-4">hola soy el header</header>
        <main className="flex flex-grow ">{children}</main>
        <footer className="bg-amber-200 text-center text-sm p-4">
          &copy; 2025 Scrapccomponentes
        </footer>
      </body>
    </html>
  );
}
